Repository CA-G12/BMS, pull requests merged in 2022-10, with the labels that each got.

#33 Add readme file
  README.md
Labels: Awaiting Review

#34 Create file structure
  .example.env
  .gitignore
  Client/.gitignore
  Client/package-lock.json
  Client/package.json
  Client/public/index.html
  Client/src/App/index.tsx
  Client/src/App/style.css
  Client/src/index.tsx
  Client/src/react-app-env.d.ts
  Client/tsconfig.json
  Server/app.ts
  Server/config/index.ts
  Server/controllers/index.ts
  Server/database/index.ts
  Server/helpers/index.ts
  Server/index.ts
  Server/interfaces/index.ts
  Server/middleware/index.ts
  Server/models/index.ts
  Server/routes/index.ts
  Server/validation/index.ts
  package.json
Labels: Approved

#36 Install antd
  client/package-lock.json
  client/package.json
  client/src/App/index.tsx
  client/src/index.tsx
  package-lock.json
Labels: Awaiting Review

#41 listening the server in browser
  .gitignore
  package-lock.json
  package.json
  server/app.ts
  server/index.ts
  tsconfig.json
Labels: Approved

#46 Install sequelize and setup its config
  package-lock.json
  package.json
  server/database/config/build.sql
  server/database/config/build.ts
  server/database/config/connection.ts
Labels: Awaiting Review

#47 Create Advertisements & Announcements models
  .eslintrc.js
  package-lock.json
  package.json
  server/database/config/connection.ts
  server/models/Advertisements.ts
  server/models/Announcements.ts
Labels: Awaiting Review

#55 setup the app and download morgan
  package-lock.json
  package.json
  server/app.ts
  server/index.ts
Labels: Priority 0, Approved

#54 Add fake data
  package.json
  server/app.ts
  server/database/config/build.ts
  server/database/config/connection.ts
  server/database/config/fakeData.ts
  server/index.ts
  server/models/Advertisement.ts
  server/models/Advertisements.ts
  server/models/Announcement.ts
  server/models/Announcements.ts
  server/models/index.ts
Labels: Approved

#49 create a services , bills , flats modules
  server/app.ts
  server/database/config/build.ts
  server/database/config/fakeData.ts
  server/models/Bill.ts
  server/models/Flat.ts
  server/models/Service.ts
  server/models/index.ts
Labels: Approved

#60 45 database create contactus complaints models
  server/app.ts
  server/database/config/build.ts
  server/database/config/fakeData.ts
  server/index.ts
  server/models/Complaints.ts
  server/models/ContactUs.ts
  server/models/index.ts
Labels: Approved

#48 Init Payments, Reviews and Users Models
  server/app.ts
  server/database/config/build.ts
  server/database/config/fakeData.ts
  server/models/Advertisement.ts
  server/models/Payment.ts
  server/models/User.ts
  server/models/index.ts
Labels: Awaiting Review

#59 Create Error Handlers & Custom Error
  server/app.ts
  server/helpers/customError.ts
  server/helpers/index.ts
  server/middleware/errors.ts
  server/middleware/index.ts
Labels: Awaiting Review

#69 Create landing: AboutUs & Advertisement components
  .eslintrc.js
  __tests__/advertisements.test.ts
  client/.eslintrc.js
  client/package-lock.json
  client/package.json
  client/src/App/index.tsx
  client/src/components/landing/AboutUs.tsx
  client/src/components/landing/AdvertisementCard.tsx
  client/src/components/landing/AdvertisementsContainer.tsx
  client/src/components/landing/Loading.tsx
  client/src/components/landing/NoData.tsx
  client/src/components/landing/Title.tsx
  client/src/components/landing/index.tsx
  client/src/pages/Landing.tsx
  client/src/pages/index.tsx
  jest.config.js
  package-lock.json
  package.json
  server/app.ts
  server/controllers/user/getAdvertisemsnts.ts
  server/controllers/user/index.ts
  server/database/config/build.ts
  server/routes/adsRouter.ts
  server/routes/index.ts
Labels: Approved

#73 create component contact us and services with ant design
  client/.eslintrc.js
  client/src/StaticData/index.ts
  client/src/components/landing/ContactUs.tsx
  client/src/components/landing/Services.tsx
  client/src/components/landing/index.tsx
  client/src/components/landing/style.css
  client/src/index.tsx
  client/src/pages/Landing.tsx
Labels: Approved

#72 create the route and the controller for flats
  __tests__/advertisements.ts
  __tests__/flat.ts
  client/src/components/landing/NoData.tsx
  server/controllers/index.ts
  server/controllers/user/getFlats.ts
  server/controllers/user/index.ts
  server/routes/adsRouter.ts
  server/routes/flatRouter.ts
  server/routes/index.ts
Labels: Awaiting Review

#71 create a free flat container component and the card componant and do…
  client/package-lock.json
  client/package.json
  client/src/App/index.tsx
  client/src/App/style.css
  client/src/components/index.tsx
  client/src/components/landing/AdvertisementCard.tsx
  client/src/components/landing/VideoSection.tsx
  client/src/components/landing/flats/FlatCard.tsx
  client/src/components/landing/flats/FlatContainer.tsx
  client/src/components/landing/flats/index.tsx
  client/src/components/landing/index.tsx
  client/src/pages/Landing.tsx
  server/controllers/user/getFlats.ts
Labels: Awaiting Review

#84 Create node.js.yml
  .github/workflows/node.js.yml
  __tests__/flat.ts
  client/package-lock.json
  client/package.json
  package-lock.json
  server/database/config/connection.ts
Labels: Awaiting Review

#91 90 edit modules interfaces
  __tests__/flat.ts
  client/package-lock.json
  package-lock.json
  server/controllers/contactus/contactus.ts
  server/database/config/build.ts
  server/database/config/fakeData.ts
  server/models/Advertisement.ts
  server/models/Announcement.ts
  server/models/Bill.ts
  server/models/Complaints.ts
  server/models/ContactUs.ts
  server/models/Flat.ts
  server/models/Payment.ts
  server/models/Service.ts
  server/models/User.ts
Labels: Awaiting Review, Priority 0

#95 83 front + back end contact page
  client/package-lock.json
  client/package.json
  client/src/Models/contactUs.ts
  client/src/Utilities/apiConsts.ts
  client/src/components/landing/ContactUs.tsx
  client/src/react-app-env.d.ts
  client/src/services/contactUsApi.ts
  package-lock.json
  server/controllers/contactus/contactus.ts
Labels: Priority 1, Approved

#89 Refactor the login
  server/controllers/Auth/login.ts
  server/middleware/auth.ts
Labels: documentation

#78 Header footer
  client/package-lock.json
  client/package.json
  client/src/App/index.tsx
  client/src/assets/images/header.png
  client/src/assets/images/map.png
  client/src/layouts/Dashbored/.gitkeep
  client/src/layouts/Landing Page/footer.tsx
  client/src/layouts/Landing Page/header.tsx
  client/src/layouts/Landing Page/layout.tsx
  client/src/layouts/Landing Page/navbar.tsx
  client/src/layouts/Landing Page/style.css
  client/src/pages/Landing.tsx
Labels: Changes Requested, Priority 1

#96 Create Admin Dashboard Layout with routing
  client/package-lock.json
  client/src/App/index.tsx
  client/src/Layouts/AdminDashboard.tsx
  client/src/Layouts/index.ts
  client/src/components/adminDashboard/bills.tsx
  client/src/components/adminDashboard/flats.tsx
  client/src/components/adminDashboard/index.tsx
  client/src/components/adminDashboard/menuList.tsx
  client/src/components/adminDashboard/navbar.tsx
  client/src/components/adminDashboard/services.tsx
  client/src/index.tsx
  client/src/router.tsx
  package-lock.json
Labels: Awaiting Review

#77 [back-end] login
  .eslintrc.js
  .example.env
  __tests__/login.ts
  package-lock.json
  server/app.ts
  server/controllers/Auth/index.ts
  server/controllers/Auth/login.ts
  server/controllers/contactus/contactus.ts
  server/database/config/fakeData.ts
  server/helpers/index.ts
  server/helpers/jwt/index.ts
  server/helpers/jwt/signToken.ts
  server/helpers/jwt/verifyToken.ts
  server/interfaces/InferUserPayload.ts
  server/middleware/auth.ts
  server/middleware/index.ts
  server/models/User.ts
  server/routes/auth.ts
  server/routes/index.ts
  server/validation/index.ts
  server/validation/loginValidation.ts
Labels: Awaiting Review

#85 create the controller for the get servcies route and return the data…
  __tests__/flat.ts
  __tests__/services.ts
  package-lock.json
  server/controllers/admin/getServices.ts
  server/controllers/admin/index.ts
  server/controllers/index.ts
  server/routes/index.ts
  server/routes/serviceRouter.ts
Labels: Awaiting Review

#99 create all routes for announcements ( get , post , delete , get by i…
  __tests__/announcement.ts
  server/controllers/Auth/index.ts
  server/controllers/advertisements/getAdvertisemsnts.ts
  server/controllers/advertisements/index.ts
  server/controllers/announcements/deleteAnnouncement.ts
  server/controllers/announcements/getAnnouncement.ts
  server/controllers/announcements/getAnnouncementById.ts
  server/controllers/announcements/index.ts
  server/controllers/announcements/postAnnouncement.ts
  server/controllers/announcements/putAnnouncement.ts
  server/controllers/auth/index.ts
  server/controllers/auth/login.ts
  server/controllers/auth/signup.ts
  server/controllers/flats/getFlats.ts
  server/controllers/flats/index.ts
  server/controllers/index.ts
  server/controllers/services/getServices.ts
  server/controllers/services/index.ts
  server/routes/announcementsRouter.ts
  server/routes/index.ts
  server/validation/announcementSchema.ts
  server/validation/index.ts
Labels: Awaiting Review

#86 create the controller for the post , put services router and return the data
  __tests__/services.ts
  server/controllers/index.ts
  server/controllers/services/index.ts
  server/controllers/services/postServices.ts
  server/controllers/services/updateServices.ts
  server/routes/serviceRouter.ts
  server/validation/index.ts
  server/validation/servicesSchema.ts
Labels: Awaiting Review

#100 make header responsive
  client/public/index.html
  client/public/logo.png
  client/src/App/index.tsx
  client/src/App/style.css
  client/src/Interfaces/contactUs.ts
  client/src/Layout/AdminDashboard.tsx
  client/src/Layout/Dashbored/.gitkeep
  client/src/Layout/LandingPage/footer.tsx
  client/src/Layout/LandingPage/header.tsx
  client/src/Layout/index.ts
  client/src/Layouts/LandingPage/footer.tsx
  client/src/Layouts/LandingPage/header.tsx
  client/src/Layouts/LandingPage/layout.tsx
  client/src/Layouts/LandingPage/navbar.tsx
  client/src/Layouts/LandingPage/style.css
  client/src/StaticData/index.ts
  client/src/Utilities/apiConsent.ts
  client/src/assets/images/logo.png
  client/src/components/AboutUs/AboutUs.tsx
  client/src/components/AboutUs/style.css
  client/src/components/AdvertisementCard/index.tsx
  client/src/components/AdvertisementsContainer/index.tsx
  client/src/components/AdvertisementsContainer/style.css
  client/src/components/ContactUs/index.tsx
  client/src/components/ContactUs/style.css
  client/src/components/FlatCard/index.tsx
  client/src/components/FlatContainer/index.tsx
  client/src/components/FlatContainer/style.css
  client/src/components/Hero/index.tsx
  client/src/components/Loading/index.tsx
  client/src/components/NoData/index.tsx
  client/src/components/Services/index.tsx
  client/src/components/Services/style.css
  client/src/components/Title/index.tsx
  client/src/components/VideoSection/index.tsx
  client/src/components/VideoSection/style.css
  client/src/components/index.tsx
  client/src/components/landing/AboutUs.tsx
  client/src/components/landing/AdvertisementCard.tsx
  client/src/components/landing/ContactUs.tsx
  client/src/components/landing/Services.tsx
  client/src/components/landing/VideoSection.tsx
  client/src/components/landing/flats/FlatCard.tsx
  client/src/components/landing/flats/index.tsx
  client/src/components/landing/index.tsx
  client/src/components/landing/style.css
  client/src/pages/Landing.tsx
  client/src/pages/index.tsx
  client/src/router.tsx
  client/src/services/contactUsApi.ts
Labels: Awaiting Review

#92 Handle GET /api/v1/flatsUsers
  __tests__/flatsUsers.ts
  server/controllers/contactus/contactus.ts
  server/controllers/flatsUsers/getFlatsUsers.ts
  server/controllers/flatsUsers/index.ts
  server/controllers/index.ts
  server/routes/flatRouter.ts
Labels: Approved

#106 make layout dashboard
  client/public/index.html
  client/src/Layout/AdminDashboard.tsx
  client/src/Layout/index.ts
  client/src/assets/images/user-photo.jpg
  client/src/components/adminDashboard/menuList.tsx
  client/src/components/adminDashboard/navbar.tsx
  client/src/components/adminDashboard/style.css
  client/src/index.tsx
  client/src/router.tsx
Labels: Awaiting Review

#101 create the tables for the services
  __tests__/services.ts
  client/src/Interfaces/addService.ts
  client/src/Interfaces/services.ts
  client/src/components/Loading/index.tsx
  client/src/components/adminDashboard/index.tsx
  client/src/components/adminDashboard/services.tsx
  client/src/components/adminDashboard/services/addService.tsx
  client/src/components/adminDashboard/services/editService.tsx
  client/src/components/adminDashboard/services/index.ts
  client/src/components/adminDashboard/services/servicesContainer.tsx
  client/src/components/adminDashboard/services/style.css
  client/src/components/index.tsx
  client/src/router.tsx
  server/controllers/index.ts
  server/controllers/services/getServiceById.ts
  server/controllers/services/getServices.ts
  server/controllers/services/index.ts
  server/controllers/services/updateServices.ts
  server/database/config/fakeData.ts
  server/routes/serviceRouter.ts
Labels: Awaiting Review

#117 create contacts table
  __tests__/contacts.ts
  client/src/components/adminDashboard/contacts/contacts.tsx
  client/src/components/adminDashboard/contacts/style.css
  client/src/components/adminDashboard/index.tsx
  client/src/components/adminDashboard/menuList.tsx
  client/src/components/index.tsx
  client/src/router.tsx
  server/controllers/contactus/getContact.ts
  server/controllers/contactus/index.ts
  server/controllers/index.ts
  server/database/config/fakeData.ts
  server/routes/contactRouter.ts
  server/routes/index.ts
Labels: Done

#113 Create Flats page with pagenation
  __tests__/flatsById.ts
  __tests__/getUsers.ts
  __tests__/updateFlat.ts
  client/package-lock.json
  client/package.json
  client/src/Interfaces/IFlatsUsersResult.ts
  client/src/components/adminDashboard/flats.tsx
  client/src/components/adminDashboard/index.tsx
  client/src/components/index.tsx
  client/src/pages/flats/Flat.tsx
  client/src/pages/flats/Flats.tsx
  client/src/pages/flats/Users.tsx
  client/src/pages/index.tsx
  client/src/router.tsx
  client/src/services/flatsUsers.ts
  server/controllers/flats/flatById.ts
  server/controllers/flats/index.ts
  server/controllers/flats/updateFlat.ts
  server/controllers/index.ts
  server/controllers/users/getUsers.ts
  server/controllers/users/index.ts
  server/models/Flat.ts
  server/routes/flatRouter.ts
  server/routes/userRoute.ts
Labels: Awaiting Review

#82 81 login front
  client/src/Interfaces/ILoginResult.ts
  client/src/Interfaces/loginModel.ts
  client/src/Layout/LandingPage/header.tsx
  client/src/Utilities/apiConsent.ts
  client/src/Utilities/apiConstatnts.ts
  client/src/assets/images/login.png
  client/src/assets/images/logo.png
  client/src/pages/Auth/Login.tsx
  client/src/router.tsx
  client/src/services/authService.ts
  client/src/services/contactUsApi.ts
  server/database/config/fakeData.ts
  server/middleware/auth.ts
Labels: Awaiting Review
